# Generated by Django 4.2.7 on 2026-01-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_archived'),
    ]

    operations = [
    ]
